# Generated by Django 4.1.7 on 2023-04-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name="nom d'utilisateur"),
        ),
    ]
